#!/bin/bash
# ----------------------------------------------------------------------------
# Uso: limpadocs
# Limpa documentos recentes no Gnome Shell (Gnome 3)
# Desde: Sáb 17 agosto 2019 01:47 BRT
# Autor: Paulo Henrique Pedro
# Versão: 1
# Licença: GPL
# ----------------------------------------------------------------------------
limpadocs(){
 # cria uma variavel local para usar no backup dos documentos baseado na data, hora, minuto e segundo,
 # ou seja, tudo pode ser controlado, se quiser depois vai lá e apaga os backups na "unha" por privacidade.
 local data=$(date +%d-%m-%Y--%H:%M:%S)
 
 # cria o backup usando o nome baseado na variavel acima
 cp /home/$USER/.local/share/recently-used.xbel /home/$USER/.local/share/bkp.$data.recently-used.xbel
 
 # remove o arquivo que salva os docs recentes
 rm /home/$USER/.local/share/recently-used.xbel
 
 # substitui o arquivo, depois o próprio Gnome formatará o arquivo
 touch /home/$USER/.local/share/recently-used.xbel
 
 # exibe uma frase para interatividade
 echo "Documentos recentes limpados com sucesso!";
 
 # sai
 exit 0;
}
limpadocs 